/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.enderfire.paiitps;

import javax.swing.JLabel;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 *
 * @author Oscar2
 */
public class MainForm extends javax.swing.JFrame {

    /**
     * Creates new form MainForm
     */
    public MainForm() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        E1N1 = new javax.swing.JTextField();
        E1N2 = new javax.swing.JTextField();
        E1Calc = new javax.swing.JButton();
        E1R1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        E2N1 = new javax.swing.JTextField();
        E2Calc = new javax.swing.JButton();
        E2R1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        E3N1 = new javax.swing.JTextField();
        E3Calc = new javax.swing.JButton();
        E3R1 = new javax.swing.JLabel();
        E3D1 = new javax.swing.JComboBox<>();
        jLabel2 = new javax.swing.JLabel();
        N1E4 = new javax.swing.JTextField();
        N2E4 = new javax.swing.JTextField();
        Calc4 = new javax.swing.JButton();
        R1E4 = new javax.swing.JLabel();
        N1E5 = new javax.swing.JTextField();
        Calc5 = new javax.swing.JButton();
        R1E5 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        Calc6 = new javax.swing.JButton();
        R1E6 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        N1E6 = new javax.swing.JTextField();
        Calc7 = new javax.swing.JButton();
        R1E7 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Calc8 = new javax.swing.JButton();
        R1E8 = new javax.swing.JLabel();
        N1E8 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Calc9 = new javax.swing.JButton();
        R1E9 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        E10N1 = new javax.swing.JTextField();
        Calc10 = new javax.swing.JButton();
        R1E10 = new javax.swing.JLabel();
        E10N2 = new javax.swing.JTextField();
        E10N3 = new javax.swing.JTextField();
        E10N4 = new javax.swing.JTextField();
        E10N5 = new javax.swing.JTextField();
        E10N6 = new javax.swing.JTextField();
        E10N7 = new javax.swing.JTextField();
        E10N8 = new javax.swing.JTextField();
        E10N9 = new javax.swing.JTextField();
        E10N10 = new javax.swing.JTextField();
        E10N11 = new javax.swing.JTextField();
        E10N12 = new javax.swing.JTextField();
        E10N13 = new javax.swing.JTextField();
        E10N14 = new javax.swing.JTextField();
        E10N15 = new javax.swing.JTextField();
        E10N16 = new javax.swing.JTextField();
        E10N17 = new javax.swing.JTextField();
        E10N18 = new javax.swing.JTextField();
        E10N19 = new javax.swing.JTextField();
        E10N20 = new javax.swing.JTextField();
        E10N21 = new javax.swing.JTextField();
        E10N22 = new javax.swing.JTextField();
        E10N23 = new javax.swing.JTextField();
        E10N24 = new javax.swing.JTextField();
        E10N25 = new javax.swing.JTextField();
        E10N26 = new javax.swing.JTextField();
        E10N27 = new javax.swing.JTextField();
        E10N28 = new javax.swing.JTextField();
        E10N29 = new javax.swing.JTextField();
        E10N30 = new javax.swing.JTextField();
        E10N31 = new javax.swing.JTextField();
        E10N32 = new javax.swing.JTextField();
        E10N33 = new javax.swing.JTextField();
        E10N34 = new javax.swing.JTextField();
        E10N35 = new javax.swing.JTextField();
        E10N36 = new javax.swing.JTextField();
        E10N37 = new javax.swing.JTextField();
        E10N38 = new javax.swing.JTextField();
        E10N39 = new javax.swing.JTextField();
        E10N40 = new javax.swing.JTextField();
        E10N41 = new javax.swing.JTextField();
        E10N42 = new javax.swing.JTextField();
        E10N43 = new javax.swing.JTextField();
        E10N44 = new javax.swing.JTextField();
        E10N45 = new javax.swing.JTextField();
        E10N46 = new javax.swing.JTextField();
        E10N47 = new javax.swing.JTextField();
        E10N48 = new javax.swing.JTextField();
        E10N49 = new javax.swing.JTextField();
        E10N50 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Ejercicio 1:");

        E1N1.setMinimumSize(new java.awt.Dimension(80, 22));
        E1N1.setPreferredSize(new java.awt.Dimension(80, 22));

        E1N2.setMinimumSize(new java.awt.Dimension(80, 22));
        E1N2.setPreferredSize(new java.awt.Dimension(80, 22));

        E1Calc.setText("Calc");
        E1Calc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E1CalcActionPerformed(evt);
            }
        });

        E1R1.setText("Resultado");

        jLabel3.setText("Ejercicio 2:");

        E2N1.setMinimumSize(new java.awt.Dimension(80, 22));
        E2N1.setPreferredSize(new java.awt.Dimension(80, 22));

        E2Calc.setText("Calc");
        E2Calc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E2CalcActionPerformed(evt);
            }
        });

        E2R1.setText("Resultado");

        jLabel5.setText("Ejercicio 3:");

        E3N1.setMinimumSize(new java.awt.Dimension(80, 22));
        E3N1.setPreferredSize(new java.awt.Dimension(80, 22));

        E3Calc.setText("Calc");
        E3Calc.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                E3CalcActionPerformed(evt);
            }
        });

        E3R1.setText("Resultado");

        E3D1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Metros a pies", "Metros a pulgadas" }));

        jLabel2.setText("Ejercicio 4:");

        N1E4.setMinimumSize(new java.awt.Dimension(80, 22));
        N1E4.setPreferredSize(new java.awt.Dimension(80, 22));

        N2E4.setMinimumSize(new java.awt.Dimension(80, 22));
        N2E4.setPreferredSize(new java.awt.Dimension(80, 22));

        Calc4.setText("Calc");
        Calc4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calc4ActionPerformed(evt);
            }
        });

        R1E4.setText("Resultado");

        N1E5.setMinimumSize(new java.awt.Dimension(80, 22));
        N1E5.setPreferredSize(new java.awt.Dimension(80, 22));

        Calc5.setText("Calc");
        Calc5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calc5ActionPerformed(evt);
            }
        });

        R1E5.setText("Resultado");

        jLabel4.setText("Ejercicio 5:");

        Calc6.setText("Calc");
        Calc6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calc6ActionPerformed(evt);
            }
        });

        R1E6.setText("Resultado");

        jLabel6.setText("Ejercicio 6 (vector separado por comas. Ej: \"0,1,2,3,4,5\"):");

        N1E6.setMinimumSize(new java.awt.Dimension(80, 22));
        N1E6.setPreferredSize(new java.awt.Dimension(80, 22));

        Calc7.setText("Calc");
        Calc7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calc7ActionPerformed(evt);
            }
        });

        R1E7.setText("Resultado");

        jLabel7.setText("Ejercicio 7:");

        Calc8.setText("Calc");
        Calc8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calc8ActionPerformed(evt);
            }
        });

        R1E8.setText("Resultado");

        N1E8.setMinimumSize(new java.awt.Dimension(80, 22));
        N1E8.setPreferredSize(new java.awt.Dimension(80, 22));

        jLabel8.setText("Ejercicio 8 (vector separado por comas):");

        Calc9.setText("Calc");
        Calc9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calc9ActionPerformed(evt);
            }
        });

        R1E9.setText("Resultado");

        jLabel9.setText("Ejercicio 9:");

        jLabel10.setText("Ejercicio 10:");

        E10N1.setMinimumSize(new java.awt.Dimension(80, 22));
        E10N1.setPreferredSize(new java.awt.Dimension(80, 22));

        Calc10.setText("Calc");
        Calc10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Calc10ActionPerformed(evt);
            }
        });

        R1E10.setText("Resultado");

        E10N2.setMinimumSize(new java.awt.Dimension(80, 22));
        E10N2.setPreferredSize(new java.awt.Dimension(80, 22));

        E10N3.setMinimumSize(new java.awt.Dimension(80, 22));
        E10N3.setPreferredSize(new java.awt.Dimension(80, 22));

        E10N4.setMinimumSize(new java.awt.Dimension(80, 22));
        E10N4.setPreferredSize(new java.awt.Dimension(80, 22));

        E10N5.setMinimumSize(new java.awt.Dimension(80, 22));
        E10N5.setPreferredSize(new java.awt.Dimension(80, 22));

        E10N6.setMinimumSize(new java.awt.Dimension(80, 22));
        E10N6.setPreferredSize(new java.awt.Dimension(80, 22));

        E10N7.setMinimumSize(new java.awt.Dimension(80, 22));
        E10N7.setPreferredSize(new java.awt.Dimension(80, 22));

        E10N8.setMinimumSize(new java.awt.Dimension(80, 22));
        E10N8.setPreferredSize(new java.awt.Dimension(80, 22));

        E10N9.setMinimumSize(new java.awt.Dimension(80, 22));
        E10N9.setPreferredSize(new java.awt.Dimension(80, 22));

        E10N10.setMinimumSize(new java.awt.Dimension(80, 22));
        E10N10.setPreferredSize(new java.awt.Dimension(80, 22));

        E10N11.setMinimumSize(new java.awt.Dimension(80, 22));
        E10N11.setPreferredSize(new java.awt.Dimension(80, 22));

        E10N12.setMinimumSize(new java.awt.Dimension(80, 22));
        E10N12.setPreferredSize(new java.awt.Dimension(80, 22));

        E10N13.setMinimumSize(new java.awt.Dimension(80, 22));
        E10N13.setPreferredSize(new java.awt.Dimension(80, 22));

        E10N14.setMinimumSize(new java.awt.Dimension(80, 22));
        E10N14.setPreferredSize(new java.awt.Dimension(80, 22));

        E10N15.setMinimumSize(new java.awt.Dimension(80, 22));
        E10N15.setPreferredSize(new java.awt.Dimension(80, 22));

        E10N16.setMinimumSize(new java.awt.Dimension(80, 22));
        E10N16.setPreferredSize(new java.awt.Dimension(80, 22));

        E10N17.setMinimumSize(new java.awt.Dimension(80, 22));
        E10N17.setPreferredSize(new java.awt.Dimension(80, 22));

        E10N18.setMinimumSize(new java.awt.Dimension(80, 22));
        E10N18.setPreferredSize(new java.awt.Dimension(80, 22));

        E10N19.setMinimumSize(new java.awt.Dimension(80, 22));
        E10N19.setPreferredSize(new java.awt.Dimension(80, 22));

        E10N20.setMinimumSize(new java.awt.Dimension(80, 22));
        E10N20.setPreferredSize(new java.awt.Dimension(80, 22));

        E10N21.setMinimumSize(new java.awt.Dimension(80, 22));
        E10N21.setPreferredSize(new java.awt.Dimension(80, 22));

        E10N22.setMinimumSize(new java.awt.Dimension(80, 22));
        E10N22.setPreferredSize(new java.awt.Dimension(80, 22));

        E10N23.setMinimumSize(new java.awt.Dimension(80, 22));
        E10N23.setPreferredSize(new java.awt.Dimension(80, 22));

        E10N24.setMinimumSize(new java.awt.Dimension(80, 22));
        E10N24.setPreferredSize(new java.awt.Dimension(80, 22));

        E10N25.setMinimumSize(new java.awt.Dimension(80, 22));
        E10N25.setPreferredSize(new java.awt.Dimension(80, 22));

        E10N26.setMinimumSize(new java.awt.Dimension(80, 22));
        E10N26.setPreferredSize(new java.awt.Dimension(80, 22));

        E10N27.setMinimumSize(new java.awt.Dimension(80, 22));
        E10N27.setPreferredSize(new java.awt.Dimension(80, 22));

        E10N28.setMinimumSize(new java.awt.Dimension(80, 22));
        E10N28.setPreferredSize(new java.awt.Dimension(80, 22));

        E10N29.setMinimumSize(new java.awt.Dimension(80, 22));
        E10N29.setPreferredSize(new java.awt.Dimension(80, 22));

        E10N30.setMinimumSize(new java.awt.Dimension(80, 22));
        E10N30.setPreferredSize(new java.awt.Dimension(80, 22));

        E10N31.setMinimumSize(new java.awt.Dimension(80, 22));
        E10N31.setPreferredSize(new java.awt.Dimension(80, 22));

        E10N32.setMinimumSize(new java.awt.Dimension(80, 22));
        E10N32.setPreferredSize(new java.awt.Dimension(80, 22));

        E10N33.setMinimumSize(new java.awt.Dimension(80, 22));
        E10N33.setPreferredSize(new java.awt.Dimension(80, 22));

        E10N34.setMinimumSize(new java.awt.Dimension(80, 22));
        E10N34.setPreferredSize(new java.awt.Dimension(80, 22));

        E10N35.setMinimumSize(new java.awt.Dimension(80, 22));
        E10N35.setPreferredSize(new java.awt.Dimension(80, 22));

        E10N36.setMinimumSize(new java.awt.Dimension(80, 22));
        E10N36.setPreferredSize(new java.awt.Dimension(80, 22));

        E10N37.setMinimumSize(new java.awt.Dimension(80, 22));
        E10N37.setPreferredSize(new java.awt.Dimension(80, 22));

        E10N38.setMinimumSize(new java.awt.Dimension(80, 22));
        E10N38.setPreferredSize(new java.awt.Dimension(80, 22));

        E10N39.setMinimumSize(new java.awt.Dimension(80, 22));
        E10N39.setPreferredSize(new java.awt.Dimension(80, 22));

        E10N40.setMinimumSize(new java.awt.Dimension(80, 22));
        E10N40.setPreferredSize(new java.awt.Dimension(80, 22));

        E10N41.setMinimumSize(new java.awt.Dimension(80, 22));
        E10N41.setPreferredSize(new java.awt.Dimension(80, 22));

        E10N42.setMinimumSize(new java.awt.Dimension(80, 22));
        E10N42.setPreferredSize(new java.awt.Dimension(80, 22));

        E10N43.setMinimumSize(new java.awt.Dimension(80, 22));
        E10N43.setPreferredSize(new java.awt.Dimension(80, 22));

        E10N44.setMinimumSize(new java.awt.Dimension(80, 22));
        E10N44.setPreferredSize(new java.awt.Dimension(80, 22));

        E10N45.setMinimumSize(new java.awt.Dimension(80, 22));
        E10N45.setPreferredSize(new java.awt.Dimension(80, 22));

        E10N46.setMinimumSize(new java.awt.Dimension(80, 22));
        E10N46.setPreferredSize(new java.awt.Dimension(80, 22));

        E10N47.setMinimumSize(new java.awt.Dimension(80, 22));
        E10N47.setPreferredSize(new java.awt.Dimension(80, 22));

        E10N48.setMinimumSize(new java.awt.Dimension(80, 22));
        E10N48.setPreferredSize(new java.awt.Dimension(80, 22));

        E10N49.setMinimumSize(new java.awt.Dimension(80, 22));
        E10N49.setPreferredSize(new java.awt.Dimension(80, 22));

        E10N50.setMinimumSize(new java.awt.Dimension(80, 22));
        E10N50.setPreferredSize(new java.awt.Dimension(80, 22));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(N1E8, javax.swing.GroupLayout.PREFERRED_SIZE, 155, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(Calc8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(R1E8, javax.swing.GroupLayout.DEFAULT_SIZE, 228, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Calc7)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(R1E7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(Calc9)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(R1E9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(N1E4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(N2E4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Calc4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(R1E4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel4)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(N1E5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Calc5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(R1E5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(E3N1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(E3D1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(E3Calc)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(E3R1, javax.swing.GroupLayout.DEFAULT_SIZE, 314, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(E2N1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(E2Calc))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                        .addComponent(jLabel1)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(E1N1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(E1N2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(E1Calc)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(E1R1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(E2R1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel10)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(E10N1, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(E10N2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(E10N3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(E10N4, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(E10N5, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(E10N7, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(E10N8, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(E10N9, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(E10N10, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(E10N6, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(E10N41, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(E10N42, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(E10N43, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(E10N44, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(E10N45, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(E10N47, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(E10N48, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(E10N49, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(E10N50, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(E10N46, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(E10N31, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(E10N32, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(E10N33, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(E10N34, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(E10N35, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(E10N37, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(E10N38, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(E10N39, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(E10N40, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(E10N36, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(E10N21, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(E10N22, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(E10N23, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(E10N24, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(E10N25, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(E10N27, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(E10N28, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(E10N29, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(E10N30, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(E10N26, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(E10N11, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(E10N12, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(E10N13, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(E10N14, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(E10N15, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(E10N17, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(E10N18, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(E10N19, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(E10N20, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(E10N16, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(R1E10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(Calc10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(N1E6, javax.swing.GroupLayout.PREFERRED_SIZE, 158, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Calc6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(R1E6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(E1N1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E1N2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E1Calc)
                    .addComponent(E1R1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(E2N1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E2Calc)
                    .addComponent(E2R1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(E3N1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(E3Calc)
                    .addComponent(E3R1)
                    .addComponent(E3D1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(N1E4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(N2E4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Calc4)
                    .addComponent(R1E4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(N1E5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Calc5)
                    .addComponent(R1E5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(N1E6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Calc6)
                    .addComponent(R1E6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Calc7)
                    .addComponent(R1E7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(N1E8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Calc8)
                    .addComponent(R1E8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(Calc9)
                    .addComponent(R1E9, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(E10N1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(Calc10)
                            .addComponent(E10N2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(E10N3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(E10N4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(E10N5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(E10N7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(E10N8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(E10N9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(E10N10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(E10N6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(E10N11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(E10N12, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(E10N13, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(E10N14, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(E10N15, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(E10N17, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(E10N18, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(E10N19, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(E10N20, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(E10N16, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(E10N21, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(E10N22, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(E10N23, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(E10N24, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(E10N25, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(E10N27, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(E10N28, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(E10N29, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(E10N30, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(E10N26, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(E10N31, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(E10N32, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(E10N33, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(E10N34, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(E10N35, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(E10N37, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(E10N38, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(E10N39, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(E10N40, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(E10N36, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(E10N41, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(E10N42, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(E10N43, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(E10N44, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(E10N45, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(E10N47, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(E10N48, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(E10N49, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(E10N50, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(E10N46, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(3, 3, 3)
                                .addComponent(R1E10, javax.swing.GroupLayout.PREFERRED_SIZE, 103, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(18, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void E1CalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E1CalcActionPerformed
        int a,b;
        
        try{
            a=Integer.parseInt(E1N1.getText());
            b=Integer.parseInt(E1N2.getText());
            E1R1.setText(String.format("Suma: %d", a+b));
        }
        catch (NumberFormatException e){
            E1R1.setText(String.format(e.getMessage()));
        }
    }//GEN-LAST:event_E1CalcActionPerformed

    private void E2CalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E2CalcActionPerformed
        int a;
        
        try{
            a=Integer.parseInt(E2N1.getText());
            E2R1.setText(String.format("Cuadrado: %d", a*a));
        }
        catch (NumberFormatException e){
            E2R1.setText(String.format(e.getMessage()));
        }
    }//GEN-LAST:event_E2CalcActionPerformed

    private void E3CalcActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_E3CalcActionPerformed
        float a;
        String unit="none";
        
        try{
            a=Integer.parseInt(E3N1.getText());
            switch(E3D1.getSelectedIndex()){
                case 1:
                    a*=12;
                    unit="Pulgadas";
                case 0:
                    a*=39.37;
                    if(unit.equals("none"))
                        unit="Pies";
                    break;
            }
            
            E3R1.setText(String.format("Resultado: %.3f %s", a,unit));
        }
        catch (NumberFormatException e){
            E1R1.setText(String.format(e.getMessage()));
        }
    }//GEN-LAST:event_E3CalcActionPerformed

    private void Calc4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calc4ActionPerformed
        int a,b;
        
        try{
            a=Integer.parseInt(N1E4.getText());
            b=Integer.parseInt(N2E4.getText());
            R1E4.setText(String.format("Hipotenusa: %.3f", Math.sqrt(a*a+b*b)));
        }
        catch (NumberFormatException e){
            E1R1.setText(String.format(e.getMessage()));
        }
        
    }//GEN-LAST:event_Calc4ActionPerformed

    private void Calc5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calc5ActionPerformed
        JLabel out=R1E5;
        double a;
        
        try{
            a=Integer.parseInt(N1E5.getText());
            for(double i=a-1;i>1;i--)
                a*=i;
            if(a<0){
            out.setText("Ingrese un numero mayor o igual a 0");
                return;
            }
            if(a<2)
                a=1;
            
            out.setText(String.format("Factorial: %.0f", a));
        }
        catch (NumberFormatException e){
            out.setText(String.format(e.getMessage()));
        }
    }//GEN-LAST:event_Calc5ActionPerformed

    private void Calc6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calc6ActionPerformed
        JLabel out=R1E6;
        
        try{
            String[] nums = N1E6.getText().split(",");
            int[] num = new int[nums.length];
            String outStr="";
            
            for(int i =0;i<nums.length;i++){
                num[i]=Integer.parseInt(nums[i]);
            }
            
            for(int i =0;i<num.length-1;i++){
                if (num[i]==0){
                    outStr+=num[i+1]+"; ";
                }
            }
            
            out.setText(outStr);
        }
        catch (NumberFormatException e){
            out.setText(String.format(e.getMessage()));
        }
    }//GEN-LAST:event_Calc6ActionPerformed

    private void Calc7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calc7ActionPerformed
        JLabel out=R1E7;
        
        try{
            int[] num = new int[10];
            num[0]=1;
            String outStr="" + num[0];
            
            for(int i = 1;i<num.length;i++){
                num[i]=i*num[i-1]+i*2;
                outStr+= "; " + num[i];
            }
            
            
            out.setText(outStr);
        }
        catch (NumberFormatException e){
            out.setText(String.format(e.getMessage()));
        }
    }//GEN-LAST:event_Calc7ActionPerformed

    private void Calc8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calc8ActionPerformed
        JLabel out=R1E8;
        
        try{
            String[] nums = N1E8.getText().split(",");
            int[] num = new int[nums.length];
            String outStr="";
            boolean minFlag=false;
            int maxpos=0;
            
            for(int i =0;i<nums.length;i++){
                num[i]=Integer.parseInt(nums[i]);
            }
            
            for(int i =0;i<num.length;i++){
                if (!minFlag && num[i]<0){
                    minFlag=true;
                    outStr+= "first value less than 0: " + num[i];
                }
                if(num[i]>num[maxpos]){
                    maxpos=i;
                }
            }
            if(!minFlag)
                outStr+= "value less than 0 not found";
            outStr+= "; max value: " + num[maxpos] + ", pos: "+maxpos;
            
            out.setText(outStr);
        }
        catch (NumberFormatException e){
            out.setText(String.format(e.getMessage()));
        }
    }//GEN-LAST:event_Calc8ActionPerformed

    private void Calc9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calc9ActionPerformed
        JLabel out=R1E9;
        int[][] num = new int[10][10];
        String outStr="<html><body>";

        for(int i = 0;i<num.length;i++){
            for(int j=0;j<num[i].length;j++){
                num[i][j] = i==j?1:0;
                outStr+= num[i][j] + ";";
                
            }
            outStr+="<br>";
        }
        outStr+="</body></html>";
        out.setText(outStr);
            
    }//GEN-LAST:event_Calc9ActionPerformed

    private void Calc10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Calc10ActionPerformed
        JLabel out=R1E10;
        String outStr="";
        JTextField[][] strNums = {
            {E10N1,E10N2,E10N3,E10N4,E10N5,E10N6,E10N7,E10N8,E10N9,E10N10},
            {E10N11,E10N12,E10N13,E10N14,E10N15,E10N16,E10N17,E10N18,E10N19,E10N20},
            {E10N21,E10N22,E10N23,E10N24,E10N25,E10N26,E10N27,E10N28,E10N29,E10N30},
            {E10N31,E10N32,E10N33,E10N34,E10N35,E10N36,E10N37,E10N38,E10N39,E10N40},
            {E10N41,E10N42,E10N43,E10N44,E10N45,E10N46,E10N47,E10N48,E10N49,E10N50},
        };
        int[][] nums = new int[5][10];
        int[] sums = new int[5];
        try{
            for(int i =0;i<strNums.length;i++){
                sums[i]=0;
                for(int j=0;j<strNums[i].length;j++){
                    nums[i][j] = Integer.parseInt(strNums[i][j].getText());
                    sums[i]+=nums[i][j];
                }
            outStr+=sums[i] + "; ";
            }
            out.setText(outStr);
        }
        catch (Exception e){
            out.setText(String.format(e.getMessage()));
        }
    }//GEN-LAST:event_Calc10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Calc10;
    private javax.swing.JButton Calc4;
    private javax.swing.JButton Calc5;
    private javax.swing.JButton Calc6;
    private javax.swing.JButton Calc7;
    private javax.swing.JButton Calc8;
    private javax.swing.JButton Calc9;
    private javax.swing.JTextField E10N1;
    private javax.swing.JTextField E10N10;
    private javax.swing.JTextField E10N11;
    private javax.swing.JTextField E10N12;
    private javax.swing.JTextField E10N13;
    private javax.swing.JTextField E10N14;
    private javax.swing.JTextField E10N15;
    private javax.swing.JTextField E10N16;
    private javax.swing.JTextField E10N17;
    private javax.swing.JTextField E10N18;
    private javax.swing.JTextField E10N19;
    private javax.swing.JTextField E10N2;
    private javax.swing.JTextField E10N20;
    private javax.swing.JTextField E10N21;
    private javax.swing.JTextField E10N22;
    private javax.swing.JTextField E10N23;
    private javax.swing.JTextField E10N24;
    private javax.swing.JTextField E10N25;
    private javax.swing.JTextField E10N26;
    private javax.swing.JTextField E10N27;
    private javax.swing.JTextField E10N28;
    private javax.swing.JTextField E10N29;
    private javax.swing.JTextField E10N3;
    private javax.swing.JTextField E10N30;
    private javax.swing.JTextField E10N31;
    private javax.swing.JTextField E10N32;
    private javax.swing.JTextField E10N33;
    private javax.swing.JTextField E10N34;
    private javax.swing.JTextField E10N35;
    private javax.swing.JTextField E10N36;
    private javax.swing.JTextField E10N37;
    private javax.swing.JTextField E10N38;
    private javax.swing.JTextField E10N39;
    private javax.swing.JTextField E10N4;
    private javax.swing.JTextField E10N40;
    private javax.swing.JTextField E10N41;
    private javax.swing.JTextField E10N42;
    private javax.swing.JTextField E10N43;
    private javax.swing.JTextField E10N44;
    private javax.swing.JTextField E10N45;
    private javax.swing.JTextField E10N46;
    private javax.swing.JTextField E10N47;
    private javax.swing.JTextField E10N48;
    private javax.swing.JTextField E10N49;
    private javax.swing.JTextField E10N5;
    private javax.swing.JTextField E10N50;
    private javax.swing.JTextField E10N6;
    private javax.swing.JTextField E10N7;
    private javax.swing.JTextField E10N8;
    private javax.swing.JTextField E10N9;
    private javax.swing.JButton E1Calc;
    private javax.swing.JTextField E1N1;
    private javax.swing.JTextField E1N2;
    private javax.swing.JLabel E1R1;
    private javax.swing.JButton E2Calc;
    private javax.swing.JTextField E2N1;
    private javax.swing.JLabel E2R1;
    private javax.swing.JButton E3Calc;
    private javax.swing.JComboBox<String> E3D1;
    private javax.swing.JTextField E3N1;
    private javax.swing.JLabel E3R1;
    private javax.swing.JTextField N1E4;
    private javax.swing.JTextField N1E5;
    private javax.swing.JTextField N1E6;
    private javax.swing.JTextField N1E8;
    private javax.swing.JTextField N2E4;
    private javax.swing.JLabel R1E10;
    private javax.swing.JLabel R1E4;
    private javax.swing.JLabel R1E5;
    private javax.swing.JLabel R1E6;
    private javax.swing.JLabel R1E7;
    private javax.swing.JLabel R1E8;
    private javax.swing.JLabel R1E9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    // End of variables declaration//GEN-END:variables
}
