/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.enderfire.paiitps.TP2Part1;

import com.enderfire.paiitps.TP2Part1.Modelo.*;

/**
 *
 * @author Oscar2
 */
public class TP2Part1Form extends javax.swing.JFrame {

    /**
     * Creates new form TP2Part1From
     */
    public TP2Part1Form() {
        initComponents();
        Carrera car1= new Carrera(0,"Ingeniería en Informática");
        Carrera car2= new Carrera(1,"Carrera 2");
        car1.addPlan(new Plan(0,"Plan 1 - 1",2000));
        car1.addPlan(new Plan(1,"Plan 2 - 1",2010));
        car1.addPlan(new Plan(2,"Plan 3 - 1",2020));
        car2.addPlan(new Plan(0,"Plan 1 - 2",2000));
        Materia[] materias = new Materia[]{
            new Materia(0,"Programacion Avanzada",2023),
            new Materia(1,"Programacion Estructurada",2023),
            new Materia(2,"Analisis Matematico",2023),
            new Materia(3,"Fisica",2023)
        };
        car1.getPlan(0).addMateria(materias[0]);
        car1.getPlan(0).addMateria(materias[1]);
        car1.getPlan(1).addMateria(materias[0]);
        car1.getPlan(1).addMateria(materias[2]);
        car1.getPlan(2).addMateria(materias[3]);
        car1.getPlan(2).addMateria(materias[2]);
        car2.getPlan(0).addMateria(materias[0]);
        car2.getPlan(0).addMateria(materias[3]);
        
        jLabel1.setText(String.format("<html><body><p>Si no se lee completo redimencionar la ventana</p><br>"
                + "%s</html></body>",
                printCarrera(car1)));
        
    }
    
    private String printCarrera(Carrera car){
        String output = String.format("<p>%s<br><br>",car.getName());
        
        for(Plan p:car.getPlanes()){
            output += String.format("%s<br>",
                    p.getName());
            for(Materia mat:p.getMaterias()){
                output += String.format("Id: %d, Nombre: %s, Año: %d<br>" ,mat.getId(),mat.getName(),mat.getAnio());    
            }
            output+="<br>";
        }
        
        
        output += "</p>";
        return output;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("jLabel1");
        jLabel1.setVerticalTextPosition(javax.swing.SwingConstants.TOP);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 288, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TP2Part1Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TP2Part1Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TP2Part1Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TP2Part1Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TP2Part1Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
