/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.enderfire.paiitps.TP3;

import com.enderfire.paiitps.TP3Part1.Models.*;
import java.util.*;

/**
 *
 * @author Oscar2
 */
public class TP3Part1Form extends javax.swing.JFrame {

    /**
     * Creates new form TP3Part1Form
     */
    public TP3Part1Form() {
        initComponents();
        
        try{
            /*Creacion de objetos*/
            Autor aut1 = new Autor("Autor 1");
            Autor aut2 = new Autor("Autor 2");
            Biblioteca biblio = new Biblioteca();
            Libro lib1=new Libro();
            lib1.setTitulo("Libro 1");
            lib1.setEdicion(2012);
            lib1.setAutor(aut1);
            List<Ejemplar> ejemplares = new ArrayList<>();
            Ejemplar ejem=new Ejemplar();
            ejem.setNroInv(1);
            ejem.setPrestado(false);
            ejem.setSale(false);
            ejemplares.add(ejem);
            ejem=new Ejemplar();
            ejem.setNroInv(2);
            ejem.setPrestado(false);
            ejem.setSale(true);
            ejemplares.add(ejem);
            ejem=new Ejemplar();
            ejem.setNroInv(3);
            ejem.setPrestado(true);
            ejem.setSale(false);
            ejemplares.add(ejem);
            ejem=new Ejemplar();
            ejem.setNroInv(4);
            ejem.setPrestado(false);
            ejem.setSale(true);
            ejemplares.add(ejem);
            lib1.setEjemplares(ejemplares);
            /*Creacion de objetos*/

            /*Impresion*/
            jLabel1.setText("<html><body>"+lib1.toString().replaceAll("\n", "<br>")+"<br><br>Ejemplares:<br>"+lib1.toStringEjemplares().replaceAll("\n", "<br>")+"</body></html>");
            /*Impresion*/
        }
        catch (Exception e){jLabel1.setText(e.getMessage());}
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jLabel1.setText("jLabel1");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, 390, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TP3Part1Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TP3Part1Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TP3Part1Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TP3Part1Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TP3Part1Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
}
