/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.enderfire.paiitps.TP3;

import javax.swing.JLabel;

/**
 *
 * @author Oscar2
 */
public class TP3Part2Form extends javax.swing.JFrame {

    /**
     * Creates new form TP3Part2Form
     */
    public TP3Part2Form() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        LabelE1 = new javax.swing.JLabel();
        InputE1 = new javax.swing.JTextField();
        CalcE1 = new javax.swing.JButton();
        ResE1 = new javax.swing.JLabel();
        ResE2 = new javax.swing.JLabel();
        LabelE2 = new javax.swing.JLabel();
        InputE2 = new javax.swing.JTextField();
        CalcE2 = new javax.swing.JButton();
        ResE3 = new javax.swing.JLabel();
        LabelE3 = new javax.swing.JLabel();
        InputE3 = new javax.swing.JTextField();
        CalcE3 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        LabelE1.setText("Ejercicio 1:");

        InputE1.setMinimumSize(new java.awt.Dimension(80, 22));
        InputE1.setPreferredSize(new java.awt.Dimension(80, 22));

        CalcE1.setText("Calc");
        CalcE1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcE1ActionPerformed(evt);
            }
        });

        ResE1.setText("Resultado");

        ResE2.setText("Resultado");

        LabelE2.setText("Ejercicio 2:");

        InputE2.setMinimumSize(new java.awt.Dimension(80, 22));
        InputE2.setPreferredSize(new java.awt.Dimension(80, 22));

        CalcE2.setText("Calc");
        CalcE2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcE2ActionPerformed(evt);
            }
        });

        ResE3.setText("Resultado");

        LabelE3.setText("Ejercicio 3:");

        InputE3.setMinimumSize(new java.awt.Dimension(80, 22));
        InputE3.setPreferredSize(new java.awt.Dimension(80, 22));

        CalcE3.setText("Calc");
        CalcE3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CalcE3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(LabelE1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InputE1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CalcE1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ResE1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelE2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InputE2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CalcE2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ResE2, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(LabelE3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(InputE3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(CalcE3)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(ResE3, javax.swing.GroupLayout.DEFAULT_SIZE, 311, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelE1)
                    .addComponent(InputE1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CalcE1)
                    .addComponent(ResE1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelE2)
                    .addComponent(InputE2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CalcE2)
                    .addComponent(ResE2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(LabelE3)
                    .addComponent(InputE3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(CalcE3)
                    .addComponent(ResE3))
                .addContainerGap(227, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void CalcE1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcE1ActionPerformed
        JLabel out=ResE1;
        
        try{
            String[] strNums = InputE1.getText().split(",");
            Integer sum=0;
            for(int i =0;i<strNums.length;i++){
                sum+=Integer.parseInt(strNums[i]);
            }
            
            out.setText("Suma: "+sum);
        }
        catch (NumberFormatException e){
            out.setText(String.format(e.getMessage()));
        }
    }//GEN-LAST:event_CalcE1ActionPerformed

    static final String[] meses = new String[]{"Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre","Octubre","Nobiembre","Diciembre"};
    private void CalcE2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcE2ActionPerformed
        JLabel out=ResE2;
        
        try{
            Integer index = Integer.parseInt(InputE2.getText());
            if(index>0 && index<13)
                out.setText("Mes: "+meses[index-1]);
            else
                out.setText("Ingrese un numero entre 1 y 12");
        }
        catch (NumberFormatException e){
            out.setText(String.format(e.getMessage()));
        }
    }//GEN-LAST:event_CalcE2ActionPerformed

    private void CalcE3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CalcE3ActionPerformed
        JLabel out=ResE3;
        String outStr="Meses que comienzan con \""+InputE3.getText()+"\": ";
        String startStr=InputE3.getText().toLowerCase();
        for(String mes:meses){
            if(mes.toLowerCase().startsWith(startStr)){
                outStr+=mes+"; ";
            }
        }
        
        out.setText(outStr.substring(0,outStr.length()-2));
    }//GEN-LAST:event_CalcE3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TP3Part2Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TP3Part2Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TP3Part2Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TP3Part2Form.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TP3Part2Form().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton CalcE1;
    private javax.swing.JButton CalcE2;
    private javax.swing.JButton CalcE3;
    private javax.swing.JTextField InputE1;
    private javax.swing.JTextField InputE2;
    private javax.swing.JTextField InputE3;
    private javax.swing.JLabel LabelE1;
    private javax.swing.JLabel LabelE2;
    private javax.swing.JLabel LabelE3;
    private javax.swing.JLabel ResE1;
    private javax.swing.JLabel ResE2;
    private javax.swing.JLabel ResE3;
    // End of variables declaration//GEN-END:variables
}
